### Bad route, 404
GET http://localhost:8080/invalid

### Method not allowed, 405
PUT http://localhost:8080/apps

### Create app, invalid maintainer email
POST http://localhost:8080/apps
Content-Type: application/json

{
	"title": "App w/ Invalid maintainer email",
	"version": "1.0.1",
	"maintainers": [
		{
			"name": "Firstname Lastname",
			"email": "apptwohotmail.com"
		}
	],
	"company": "Upbound Inc.",
	"website": "https://upbound.io",
	"source": "https://github.com/upbound/repo",
	"license": "Apache-2.0",
	"description": "### blob of markdown\nMore markdown\n"
}

### Create app, missing version field
POST http://localhost:8080/apps
Content-Type: application/json

{
	"title": "App w/ missing version",
	"maintainers": [
		{
			"name": "first last",
			"email": "email@hotmail.com"
		},
		{
			"name": "first last",
			"email": "email@gmail.com"
		}
	],
	"company": "Company Inc.",
	"website": "https://website.com",
	"source": "https://github.com/company/repo",
	"license": "Apache-2.0",
	"description": "### blob of markdown\nMore markdown\n"
}

### Create app, all valid
POST http://localhost:8080/apps
Content-Type: application/json

{
	"title": "Valid App 1",
	"version": "0.0.1",
	"maintainers": [
		{
			"name": "firstmaintainer app1",
			"email": "firstmaintainer@hotmail.com"
		},
		{
			"name": "secondmaintainer app1",
			"email": "secondmaintainer@gmail.com"
		}
	],
	"company": "Random Inc.",
	"website": "https://website.com",
	"source": "https://github.com/random/repo",
	"license": "Apache-2.0",
	"description": "### Interesting Title\nSome application content, and description\n"
}

### Get an app
GET http://localhost:8080/apps/9422a295-f370-4423-b8c2-7128b2b8200e

###

